name: shift6
version: '3.8'

deploy:
  type: docker-compose
  dockerfile_path: deploy/coolify/Dockerfile
  compose_file: deploy/coolify/docker-compose.yml

ports:
  - 3000:80

environment:
  NODE_ENV: production