import type {
  ExperienceLevel,
  Goal,
  Program,
  ProgramVersion,
  ProgressionStrategy,
} from './types';
import { buildLaunchProgramVersion } from './fixtures/programVersions';
import { demoProgramVersion } from './fixtures/home';

const metadata: readonly Omit<
  Program,
  'currentVersionId' | 'isTemplate'
>[] = [
  {
    id: 'program-barbell-30',
    slug: 'barbell-30',
    title: 'Barbell 30',
    description: 'Efficient strength sessions with easy cardio between lifts.',
    goals: ['strength', 'consistent-training'],
    targetUser: 'People who want a long-term barbell framework in about 30 minutes.',
    experience: ['beginner', 'intermediate'],
    daysPerWeek: 3,
    sessionLengthMinutes: 30,
    requiredEquipmentIds: ['equipment-barbell', 'equipment-plates', 'equipment-rack'],
    optionalEquipmentIds: ['equipment-bench', 'equipment-pull-up-bar', 'equipment-bike'],
    progressionStrategy: 'double-progression',
  },
  {
    id: 'program-beginner-strength',
    slug: 'beginner-strength',
    title: 'Beginner Strength',
    description: 'A calm introduction to repeatable full-body strength training.',
    goals: ['strength', 'consistent-training'],
    targetUser: 'New lifters who want simple sessions and clear progression.',
    experience: ['beginner'],
    daysPerWeek: 3,
    sessionLengthMinutes: 30,
    requiredEquipmentIds: ['equipment-dumbbells'],
    optionalEquipmentIds: ['equipment-bench', 'equipment-resistance-bands'],
    progressionStrategy: 'double-progression',
  },
  {
    id: 'program-full-body-strength',
    slug: 'full-body-strength',
    title: 'Full Body Strength',
    description: 'Three balanced sessions covering the major movement patterns.',
    goals: ['strength', 'general-health'],
    targetUser: 'Lifters who prefer training the whole body each session.',
    experience: ['beginner', 'intermediate'],
    daysPerWeek: 3,
    sessionLengthMinutes: 45,
    requiredEquipmentIds: ['equipment-dumbbells', 'equipment-bench'],
    optionalEquipmentIds: ['equipment-cable-machine'],
    progressionStrategy: 'linear-load',
  },
  {
    id: 'program-strength-conditioning',
    slug: 'strength-conditioning',
    title: 'Strength + Conditioning',
    description: 'Strength foundations paired with practical aerobic work.',
    goals: ['strength', 'conditioning'],
    targetUser: 'People who want stronger lifts and better work capacity.',
    experience: ['intermediate', 'advanced'],
    daysPerWeek: 4,
    sessionLengthMinutes: 45,
    requiredEquipmentIds: ['equipment-dumbbells'],
    optionalEquipmentIds: ['equipment-bike', 'equipment-rower', 'equipment-kettlebell'],
    progressionStrategy: 'cardio',
  },
  {
    id: 'program-hypertrophy',
    slug: 'hypertrophy',
    title: 'Hypertrophy',
    description: 'Structured volume and rep progression for building muscle.',
    goals: ['muscle', 'consistent-training'],
    targetUser: 'Intermediate lifters ready to make volume more intentional.',
    experience: ['intermediate', 'advanced'],
    daysPerWeek: 4,
    sessionLengthMinutes: 60,
    requiredEquipmentIds: ['equipment-dumbbells', 'equipment-bench'],
    optionalEquipmentIds: ['equipment-cable-machine', 'equipment-selectorized-machine'],
    progressionStrategy: 'volume',
  },
  {
    id: 'program-upper-lower',
    slug: 'upper-lower',
    title: 'Upper / Lower',
    description: 'A flexible four-day split with space to build and recover.',
    goals: ['strength', 'muscle'],
    targetUser: 'Lifters who want focused sessions across four weekly days.',
    experience: ['intermediate', 'advanced'],
    daysPerWeek: 4,
    sessionLengthMinutes: 50,
    requiredEquipmentIds: ['equipment-barbell', 'equipment-plates', 'equipment-rack'],
    optionalEquipmentIds: ['equipment-bench', 'equipment-cable-machine'],
    progressionStrategy: 'double-progression',
  },
  {
    id: 'program-push-pull-legs',
    slug: 'push-pull-legs',
    title: 'Push / Pull / Legs',
    description: 'A classic three-day split with optional repeat sessions.',
    goals: ['muscle', 'strength'],
    targetUser: 'Experienced lifters who like a focused movement split.',
    experience: ['intermediate', 'advanced'],
    daysPerWeek: 3,
    sessionLengthMinutes: 60,
    requiredEquipmentIds: ['equipment-dumbbells'],
    optionalEquipmentIds: ['equipment-cable-machine', 'equipment-bench'],
    progressionStrategy: 'rep-target',
  },
  {
    id: 'program-dumbbell-only',
    slug: 'dumbbell-only',
    title: 'Dumbbell Only',
    description: 'A complete six-week plan built around a pair of dumbbells.',
    goals: ['strength', 'muscle', 'general-health'],
    targetUser: 'People training at home or in a gym without a barbell.',
    experience: ['beginner', 'intermediate'],
    daysPerWeek: 3,
    sessionLengthMinutes: 30,
    requiredEquipmentIds: ['equipment-dumbbells'],
    optionalEquipmentIds: ['equipment-bench'],
    progressionStrategy: 'double-progression',
  },
  {
    id: 'program-home-gym',
    slug: 'home-gym',
    title: 'Home Gym',
    description: 'Balanced training for the equipment you keep close to home.',
    goals: ['general-health', 'strength'],
    targetUser: 'Home-gym users who want a flexible all-round framework.',
    experience: ['beginner', 'intermediate'],
    daysPerWeek: 4,
    sessionLengthMinutes: 45,
    requiredEquipmentIds: ['equipment-dumbbells'],
    optionalEquipmentIds: ['equipment-kettlebell', 'equipment-resistance-bands'],
    progressionStrategy: 'linear-load',
  },
  {
    id: 'program-minimal-equipment',
    slug: 'minimal-equipment',
    title: 'Minimal Equipment',
    description: 'Make consistent progress with bodyweight, bands, and one weight.',
    goals: ['general-health', 'consistent-training'],
    targetUser: 'Busy people who want a useful plan with very little setup.',
    experience: ['beginner', 'intermediate'],
    daysPerWeek: 3,
    sessionLengthMinutes: 20,
    requiredEquipmentIds: ['equipment-bodyweight'],
    optionalEquipmentIds: ['equipment-resistance-bands', 'equipment-kettlebell'],
    progressionStrategy: 'rep-target',
  },
  {
    id: 'program-bodyweight-foundations',
    slug: 'bodyweight-foundations',
    title: 'Bodyweight Foundations',
    description: 'Build strength, control, and confidence without external load.',
    goals: ['general-health', 'strength', 'mobility'],
    targetUser: 'Beginners who want a no-gym starting point.',
    experience: ['beginner'],
    daysPerWeek: 3,
    sessionLengthMinutes: 20,
    requiredEquipmentIds: ['equipment-bodyweight'],
    optionalEquipmentIds: ['equipment-pull-up-bar'],
    progressionStrategy: 'skill',
  },
  {
    id: 'program-resistance-bands',
    slug: 'resistance-bands',
    title: 'Resistance Bands',
    description: 'Portable resistance training with clear rep and tempo targets.',
    goals: ['strength', 'general-health'],
    targetUser: 'People who train while travelling or with limited space.',
    experience: ['beginner', 'intermediate'],
    daysPerWeek: 3,
    sessionLengthMinutes: 30,
    requiredEquipmentIds: ['equipment-resistance-bands'],
    optionalEquipmentIds: ['equipment-bodyweight'],
    progressionStrategy: 'rep-target',
  },
  {
    id: 'program-general-fitness',
    slug: 'general-fitness',
    title: 'General Fitness',
    description: 'A balanced mix of strength, cardio, mobility, and recovery.',
    goals: ['general-health', 'conditioning', 'consistent-training'],
    targetUser: 'Anyone who wants a sustainable, varied weekly routine.',
    experience: ['beginner', 'intermediate', 'advanced'],
    daysPerWeek: 4,
    sessionLengthMinutes: 30,
    requiredEquipmentIds: ['equipment-bodyweight'],
    optionalEquipmentIds: ['equipment-dumbbells', 'equipment-bike'],
    progressionStrategy: 'cardio',
  },
  {
    id: 'program-strength-longevity',
    slug: 'strength-for-longevity',
    title: 'Strength for Longevity',
    description: 'Strength, balance, aerobic capacity, and mobility for the long term.',
    goals: ['healthy-ageing', 'strength', 'mobility'],
    targetUser: 'Adults who want training that supports a capable everyday life.',
    experience: ['beginner', 'intermediate'],
    daysPerWeek: 3,
    sessionLengthMinutes: 30,
    requiredEquipmentIds: ['equipment-bodyweight'],
    optionalEquipmentIds: ['equipment-dumbbells', 'equipment-bike'],
    progressionStrategy: 'skill',
  },
  {
    id: 'program-athletic-conditioning',
    slug: 'athletic-conditioning',
    title: 'Athletic Conditioning',
    description: 'Power, repeatable conditioning, and movement quality in one block.',
    goals: ['athletic-performance', 'conditioning'],
    targetUser: 'Athletes and active people who want useful conditioning.',
    experience: ['intermediate', 'advanced'],
    daysPerWeek: 4,
    sessionLengthMinutes: 45,
    requiredEquipmentIds: ['equipment-bodyweight'],
    optionalEquipmentIds: [
      'equipment-medicine-ball',
      'equipment-kettlebell',
      'equipment-rower',
    ],
    progressionStrategy: 'density',
  },
  {
    id: 'program-mobility-strength',
    slug: 'mobility-strength',
    title: 'Mobility + Strength',
    description: 'Move well, build resilient strength, and keep sessions approachable.',
    goals: ['mobility', 'general-health', 'strength'],
    targetUser: 'People who want strength training with mobility built in.',
    experience: ['beginner', 'intermediate'],
    daysPerWeek: 3,
    sessionLengthMinutes: 30,
    requiredEquipmentIds: ['equipment-bodyweight'],
    optionalEquipmentIds: ['equipment-resistance-bands', 'equipment-dumbbells'],
    progressionStrategy: 'skill',
  },
  {
    id: 'program-kettlebell',
    slug: 'kettlebell',
    title: 'Kettlebell',
    description: 'Simple kettlebell strength and conditioning across six weeks.',
    goals: ['strength', 'conditioning'],
    targetUser: 'People who enjoy full-body training with one versatile weight.',
    experience: ['beginner', 'intermediate'],
    daysPerWeek: 3,
    sessionLengthMinutes: 30,
    requiredEquipmentIds: ['equipment-kettlebell'],
    optionalEquipmentIds: ['equipment-bodyweight'],
    progressionStrategy: 'density',
  },
  {
    id: 'program-express-20',
    slug: 'express-20',
    title: 'Express 20',
    description: 'Short, focused sessions for weeks when time is the constraint.',
    goals: ['consistent-training', 'general-health'],
    targetUser: 'Busy people who want a complete training habit in 20 minutes.',
    experience: ['beginner', 'intermediate', 'advanced'],
    daysPerWeek: 4,
    sessionLengthMinutes: 20,
    requiredEquipmentIds: ['equipment-bodyweight'],
    optionalEquipmentIds: ['equipment-dumbbells'],
    progressionStrategy: 'density',
  },
  {
    id: 'program-three-day-gym',
    slug: 'three-day-gym',
    title: '3-Day Gym',
    description: 'A flexible gym plan that makes three weekly visits count.',
    goals: ['strength', 'muscle', 'consistent-training'],
    targetUser: 'Gym members who want an efficient three-day structure.',
    experience: ['beginner', 'intermediate'],
    daysPerWeek: 3,
    sessionLengthMinutes: 45,
    requiredEquipmentIds: ['equipment-dumbbells'],
    optionalEquipmentIds: ['equipment-barbell', 'equipment-cable-machine'],
    progressionStrategy: 'double-progression',
  },
  {
    id: 'program-four-day-gym',
    slug: 'four-day-gym',
    title: '4-Day Gym',
    description: 'A progressive four-day gym framework for steady, measurable training.',
    goals: ['strength', 'muscle'],
    targetUser: 'Intermediate lifters ready for more weekly structure.',
    experience: ['intermediate', 'advanced'],
    daysPerWeek: 4,
    sessionLengthMinutes: 60,
    requiredEquipmentIds: ['equipment-dumbbells', 'equipment-bench'],
    optionalEquipmentIds: ['equipment-barbell', 'equipment-cable-machine'],
    progressionStrategy: 'volume',
  },
];

export type ProgramCatalogueStatus = 'published' | 'metadata-draft';
export type ProgramBuildStatus = 'canonical' | 'executable-draft' | 'metadata-only';

export interface ProgramCatalogueEntry {
  program: Program;
  status: ProgramCatalogueStatus;
  buildStatus: ProgramBuildStatus;
  version?: ProgramVersion;
}

export const programLibrary: readonly ProgramCatalogueEntry[] = metadata.map((entry, index) => {
  const currentVersionId = index === 0 ? demoProgramVersion.id : `${entry.id}-version-1`;
  const program: Program = {
    ...entry,
    currentVersionId,
    isTemplate: true,
  };
  const version = index === 0 ? demoProgramVersion : buildLaunchProgramVersion(program);

  return {
    program,
    status: index === 0 ? 'published' : 'metadata-draft',
    buildStatus:
      index === 0 ? 'canonical' : version === undefined ? 'metadata-only' : 'executable-draft',
    ...(version ? { version } : {}),
  };
});

export const programLibraryPrograms = programLibrary.map((entry) => entry.program);

export function getProgramCatalogueStatusLabel(status: ProgramCatalogueStatus): string {
  return status === 'published' ? 'Ready to start' : 'Content in build';
}

export type ProgramGoal = Goal;
export type ProgramExperience = ExperienceLevel;
export type ProgramStrategy = ProgressionStrategy;
